# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-12-23 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnquieyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('courses', multiselectfield.db.fields.MultiSelectField(choices=[('PTYHON', 'Python'), ('DJANGO', 'Django'), ('UI', 'Ui'), ('REST API', 'Rest Api')], max_length=200)),
                ('trainers', multiselectfield.db.fields.MultiSelectField(choices=[('SAI', 'Sai'), ('NANI', 'Nani'), ('SATYA', 'Satya')], max_length=200)),
                ('branches', multiselectfield.db.fields.MultiSelectField(choices=[('HYD', 'Hyd'), ('BANG', 'Bang'), ('CHENNAI', 'Chennai')], max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('start_date', models.DateField(max_length=100)),
            ],
        ),
    ]
